### PR TITLE
Remove YUI

### PR DESCRIPTION
**Pull request by mawinter69**
remote the yui tree view and replace with jelly based rendering with some small javascript to show/hide subtrees

remove yui cookie and remove cookie script from core

This change is based on top of #36

After:
image
image

### Testing done
Manual testing

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by gounthar** [comment]
It does not build, unfortunately.

**Review by basil — APPROVED** [review]
Thanks for the PR!

**Comment by basil** [comment]
@mbSmaga Are you interested in cutting a release? If not, perhaps @mawinter69 might be interested in temporarily adopting this plugin to release it.

**Comment by basil** [comment]
@mawinter69 Any interest in adopting this plugin to perform a release?

**Comment by mbSmaga** [comment]
@basil released under https://github.com/jenkinsci/sectioned-view-plugin/releases/tag/sectioned-view-1.28 , apologies for not noticing your comment earlier.

**Comment by basil** [comment]
@mbsmaga Thank you very much!

**Comment by basil** [comment]
@mawinter69 Is it an issue that there is still a reference to YUI treeview here:

```xml
src/main/resources/hudson/plugins/sectioned_view/SectionedView/configure-entries.jelly
31:  <l:yui module="treeview" />
```

**Comment by mawinter69** [comment]
should be removed, seems I missed that, not sure what will happen when yui is completely removed from core and the taglib no longer exists.

**Comment by basil** [comment]
Thanks @mawinter69! I have filed [JENKINS-75013](https://issues.jenkins.io/browse/JENKINS-75013) to track the removal of this code.

**Pull request merged**
