### PR TITLE
[JENKINS-29250] Sectioned View appearance broken in 1.619

### PR DESCRIPTION
**Pull request by recena**
This PR fixes [JENKINS-29250](https://issues.jenkins-ci.org/browse/JENKINS-29250), see attached screenshots in the Jira issue itself.

This bug is derived from [JENKINS-28550](https://issues.jenkins-ci.org/browse/JENKINS-28550).

### CODE REVIEW

**Comment by recena** [comment]
@reviewbybees Could you review these changes? Specially, @daniel-beck

**Comment by tfennelly** [comment]
Hey @recena, can you explain what this is fixing and maybe provide before and after screenshots?

**Comment by recena** [comment]
@tfennelly Description updated.

**Comment by daniel-beck** [comment]
For future reference: Fixing commits should say `[FIX JENKINS-…]` so the bot resolves the issue when this gets merged. See https://wiki.jenkins-ci.org/display/JENKINS/contributing *Commit Messages*.

**Comment by daniel-beck** [comment]
What happens when you install this on an older version of Jenkins, e.g. only update the plugin, but not Jenkins itself?

**Comment by recena** [comment]
@daniel-beck I'm not sure, but I can try it. For example, I can try it with Jenkins version prior to 1.619.

**Comment by recena** [comment]
@daniel-beck Other option would be to set Jenkins Core baseline to 1.619. This plugin has slow activity.

**Comment by recena** [comment]
@daniel-beck I've tried with **Jenkins 1.618** and looks great.

jenkins-29250_1

**Comment by stephenc** [comment]
@recena can you give a before screenshot with 1.618 also so that we can see the effect on versions before the fix is needed.

If the diff is excessive you can always use a jelly condition in https://github.com/jenkinsci/sectioned-view-plugin/blob/master/src/main/resources/hudson/plugins/sectioned_view/SectionedViewPageDecorator/header.jelly to switch behaviour based on Jenkins version, e.g.

```
<j:if test='${app.version &gt;= "1.619"}'>
  ... include the fixup css
</j:if>
```

**NOTE:** the test in there is not quite correct as you really need to be using `VersionNumber.isOlderThan(VersionNumber)` rather than string comparison... but that would involve exposing the version number check in the `SectionedViewPageDecorator` class so you can do `test="${it.jenkins_1_619_orNewer}"` to call into `boolean SectionedViewPageDecorator.isJenkins_1_619_orNewer() { return !Jenkins.getVersion().isOlderThan(new VersionNumber("1.619")); }`

**Comment by stephenc** [comment]
To clarify the previous comment. I am just suggesting a workaround **if** the diff on pre-1.619 is excessive. I suspect it is minimal and we should be ok

**Comment by recena** [comment]
@stephenc In advance, thanks for your feedback. You can find these screenshots in the [issue](https://issues.jenkins-ci.org/browse/JENKINS-29250). My proposal is working fine with different Jenkins version. It was an easy solution.

**Comment by stephenc** [comment]
@recena the screenshots in the issue are not a like for like comparison with the screenshot in this PR.

I would like to be able to compare the difference of **the same** view in 1.618 before and after this fix. (Same goes for 1.619 but less important to have that)

**Comment by recena** [comment]
@stephenc I'll attach the screenshots this night.

**Comment by recena** [comment]
@stephenc Please, find attached two screenshots. The same content in Jenkins 1.618 & Jenkins 1.619

jenkins-29250_1618

jenkins-29250_1619

**Comment by stephenc** [comment]
Yes I have no doubt that the 1.618-with-patch vs 1.619-with-patch is negligible in diff.

What I was asking for was 1.618-without-patch vs 1.618-with-patch to see if the patch affects older versions of Jenkins that do not need the patch (ie to answer the question: do we need to bump the minimum version of Jenkins to 1.619)

**Comment by recena** [comment]
@stephenc What patch?

This PR aims to solve a (*litlle bit*) compatibility problem with a important UI (layout) [change](https://github.com/jenkinsci/jenkins/pull/1717) introduced in Jenkins 1.609. This PR is working fine with Jenkins version prior to 1.608 and the last release, 1.609.

**1.618-with-patch** does not make sense.

**Comment by recena** [comment]
@tfennelly @gusreiber Could you review these changes? Thanks in advance.

**Comment by stephenc** [comment]
1.618-with-patch is a Jenkins 1.618 running this plugin with the PR applied
1.618-without-patch is a Jenkins 1.618 running this plugin without the PR applied

IOW what effect does this PR have on a Jenkins that does not need this PR.

If the answer is none or just a few pixels then I'm fine. I expect that I am fine. If the answer is bigger than that, then there are two options: 

1. tweak the CSS change a tad
2. set the minimum version of Jenkins in the pom to 1.619

I prefer 1 if it comes to it, but I just want the screenshots so that we can confirm that this is not an issue

**Comment by recena** [comment]
@stephenc Ok, I'll send you later. I'm sorry for the misunderstanding.

**Comment by recena** [comment]
@stephenc Please, find two screenshots:

## Jenkins 1.618 without this PR:
jenkins-29250_1618_withoutpr

## Jenkins 1.618 with this PR:
jenkins-29250_1618_withpr

Obviously, I did not try so much examples, but I think that this PR solve the bug.

**Comment by stephenc** [comment]
:bee:

**Comment by recena** [comment]
@stephenc you rock!

**Comment by daniel-beck** [comment]
:bee:

**Comment by recena** [comment]
@daniel-beck Thanks!

**Pull request merged**
